"""Initial migration

Revision ID: a39f52f84b96
Revises: 
Create Date: 2025-09-18 16:43:37.350112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39f52f84b96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'version', name='uix_number_version')
    )
    op.create_index(op.f('ix_documents_date'), 'documents', ['date'], unique=False)
    op.create_index(op.f('ix_documents_number'), 'documents', ['number'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_document_point_number', 'points', ['document_id', 'number'], unique=False)
    op.create_index(op.f('ix_points_number'), 'points', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_number'), table_name='points')
    op.drop_index('idx_document_point_number', table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_documents_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_date'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
